CREATE DATABASE payment_gateway;

use payment_gateway;


CREATE TABLE Accounts (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    balance DECIMAL(15, 2) NOT NULL DEFAULT 0.00 CHECK (balance >= 0),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE Merchants (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE Transactions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    STATUS ENUM('PENDING', 'PROCESSING', 'APPROVED', 'DECLINED', 'REFUNDED') NOT NULL,
    account_id BIGINT NOT NULL,
    merchant_id BIGINT NOT NULL,
    amount DECIMAL(15, 2) NOT NULL CHECK (amount > 0),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (account_id) REFERENCES Accounts(id) ON DELETE CASCADE,
    FOREIGN KEY (merchant_id) REFERENCES Merchants(id) ON DELETE CASCADE
);


